In [2]:
import email
import getpass,imaplib
import os
import sys
import numpy as np
import pandas as pd
import json
import pandas.io.gbq as gbq
from google.cloud import bigquery

In [ ]:
detach_dir = '.'

In [ ]:
if 'attachments' not in os.listdir(detach_dir):
    os.mkdir('attachments')

In [3]:
userName = 'codebalanceit@gmail.com'
password = 'Hari@coding'

In [4]:
imapSession = imaplib.IMAP4_SSL('imap.gmail.com')
typ, accountDetails = imapSession.login(userName, password)

imapSession.select()
typ, data = imapSession.search(None, '(FROM "sreehari nambiar") UNSEEN')

# iterate over all emails
for msgId in data[0].split():
    typ, messageParts = imapSession.fetch(msgId, '(RFC822)')
    # print(emailBody)
    emailBody = messageParts[0][1]
    mail = email.message_from_bytes(emailBody)
    for part in mail.walk():
        if part.get_content_maintype() == 'multipart':
            # print part.as_string()
            continue
        if part.get('Content-Disposition') is None:
            # print part.as_string()
            continue
        fileName = part.get_filename()
        #print(fileName)
        
            
#         if bool(fileName):
#             filePath = os.path.join(detach_dir, 'attachments', fileName)
#             if not os.path.isfile(filePath):
#                 #print(filePath) 
#                 fp = open(filePath, 'wb')
#                 fp.write(part.get_payload(decode=True))
#                 fp.close()
    imapSession.store(msgId, '+FLAGS', '\Seen')
            
imapSession.close()
imapSession.logout()

## update control table

('BYE', [b'LOGOUT Requested'])

In [5]:
fileName

'Sales and Inventory Report - 2018 FW06 - KOCO LIFE (49509).xlsx'

In [6]:
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="C:\MY DOCUMENTS\Perssonal Projects\social analysis\datamaster-master\sarasmaster-a88d695c46b1.json"

In [ ]:
# Import the Google Cloud client Library
from google.cloud import storage
from google.cloud.exceptions import NotFound

In [ ]:
def upload_blob(bucket_name, source_file_name, destination_blob_name):
    # upload a file to bucket
    # Initiate a client
    storage_client = storage.Client()
    bucket = storage_client.get_bucket(bucket_name)
    blob = bucket.blob(destination_blob_name)
    
    blob.upload_from_filename(source_file_name)
    
    print('File {} uploaded to {}.'.format(source_file_name,
        destination_blob_name))

In [ ]:
upload_blob('sarasmaster', fileName, 'kopari/retail/ulta/ulta_sales.xls')

In [7]:
import pandas as pd
import json
import pandas.io.gbq as gbq
from google.cloud import bigquery
# desired_cols = [1] + list(range(19,43))
result = pd.read_excel(fileName, sheetname=0)
df_result = pd.DataFrame(result)
df_result.head(10)

                                                                         Weekly Sales and Inventory Report  \
NaN NaN                                                NaN            Last Closed Week Sales and Inventory
                                                       NaN          Fiscal Week 6: 03/11/2018 - 03/17/2018
                                                       NaN                                             NaN
                                                       NaN                                             NaN
    KOCO LIFE (49509)                                  NaN                                             NaN
     Please Note:  Inventory values are from a snap... NaN                                             NaN
    Vendor #                                           Vendor Name                             Item Number
    NaN                                                NaN                                             NaN
    49509                                              KOCO LIFE                                   2523646
                                                       KOCO LIFE                                   2523647

                                                                                             Unnamed: 1  \
NaN NaN                                                NaN                                          NaN
                                                       NaN                                          NaN
                                                       NaN                                          NaN
                                                       NaN                                          NaN
    KOCO LIFE (49509)                                  NaN                                          NaN
     Please Note:  Inventory values are from a snap... NaN                                          NaN
    Vendor #                                           Vendor Name                     Item Description
    NaN                                                NaN                                          NaN
    49509                                              KOCO LIFE      KOPARI  COCONUT ROSE TONER 5.10OZ
                                                       KOCO LIFE    KOPARI COCONUT MULTITASKING KIT.COM

                                                                   Unnamed: 2  \
NaN NaN                                                NaN                NaN
                                                       NaN                NaN
                                                       NaN                NaN
                                                       NaN                NaN
    KOCO LIFE (49509)                                  NaN                NaN
     Please Note:  Inventory values are from a snap... NaN                NaN
    Vendor #                                           Vendor Name        Div
    NaN                                                NaN                NaN
    49509                                              KOCO LIFE            1
                                                       KOCO LIFE            1

                                                                   Unnamed: 3  \
NaN NaN                                                NaN                NaN
                                                       NaN                NaN
                                                       NaN                NaN
                                                       NaN                NaN
    KOCO LIFE (49509)                                  NaN                NaN
     Please Note:  Inventory values are from a snap... NaN                NaN
    Vendor #                                           Vendor Name       Dept
    NaN                                                NaN                NaN
    49509                                              KOCO LIFE           14
                                                       KOCO LIFE           14

                                                                   Unnamed: 4  \
NaN NaN                                                NaN                NaN
                                                       NaN                NaN
                                                       NaN                NaN
                                                       NaN                NaN
    KOCO LIFE (49509)                                  NaN                NaN
     Please Note:  Inventory values are from a snap... NaN                NaN
    Vendor #                                           Vendor Name      Class
    NaN                                                NaN                NaN
    49509                                              KOCO LIFE          115
                                                       KOCO LIFE          116

                                                                   Unnamed: 5  \
NaN NaN                                                NaN                NaN
                                                       NaN                NaN
                                                       NaN                NaN
                                                       NaN                NaN
    KOCO LIFE (49509)                                  NaN                NaN
     Please Note:  Inventory values are from a snap... NaN                NaN
    Vendor #                                           Vendor Name  Sub Class
    NaN                                                NaN                NaN
    49509                                              KOCO LIFE         2168
                                                       KOCO LIFE         1172

                                                                    Unnamed: 6  \
NaN NaN                                                NaN                 NaN
                                                       NaN                 NaN
                                                       NaN                 NaN
                                                       NaN                 NaN
    KOCO LIFE (49509)                                  NaN                 NaN
     Please Note:  Inventory values are from a snap... NaN                 NaN
    Vendor #                                           Vendor Name  Item\nRank
    NaN                                                NaN                 NaN
    49509                                              KOCO LIFE             F
                                                       KOCO LIFE             #

                                                                               Unnamed: 7  \
NaN NaN                                                NaN                            NaN
                                                       NaN                            NaN
                                                       NaN                            NaN
                                                       NaN                            NaN
    KOCO LIFE (49509)                                  NaN                            NaN
     Please Note:  Inventory values are from a snap... NaN                            NaN
    Vendor #                                           Vendor Name  Store\nCount\n(Total)
    NaN                                                NaN                            NaN
    49509                                              KOCO LIFE                     1096
                                                       KOCO LIFE                      NaN

                                                                      Unnamed: 8  \
NaN NaN                                                NaN                   NaN
                                                       NaN                   NaN
                                                       NaN                   NaN
                                                       NaN                   NaN
    KOCO LIFE (49509)                                  NaN                   NaN
     Please Note:  Inventory values are from a snap... NaN                   NaN
    Vendor #                                           Vendor Name           UPC
    NaN                                                NaN                   NaN
    49509                                              KOCO LIFE    851989006084
                                                       KOCO LIFE    851989006282

                                                                         Unnamed: 9  \
NaN NaN                                                NaN                      NaN
                                                       NaN                      NaN
                                                       NaN                      NaN
                                                       NaN                      NaN
    KOCO LIFE (49509)                                  NaN                      NaN
     Please Note:  Inventory values are from a snap... NaN                      NaN
    Vendor #                                           Vendor Name  Vendor Part No.
    NaN                                                NaN                      NaN
    49509                                              KOCO LIFE           KRT-0150
                                                       KOCO LIFE           KMK-0200

                                                                          ...          \
NaN NaN                                                NaN                ...
                                                       NaN                ...
                                                       NaN                ...
                                                       NaN                ...
    KOCO LIFE (49509)                                  NaN                ...
     Please Note:  Inventory values are from a snap... NaN                ...
    Vendor #                                           Vendor Name        ...
    NaN                                                NaN                ...
    49509                                              KOCO LIFE          ...
                                                       KOCO LIFE          ...

                                                                            Unnamed: 61  \
NaN NaN                                                NaN                          NaN
                                                       NaN                          NaN
                                                       NaN                          NaN
                                                       NaN                          NaN
    KOCO LIFE (49509)                                  NaN                          NaN
     Please Note:  Inventory values are from a snap... NaN                          NaN
    Vendor #                                           Vendor Name  STORE\nEOH (LY)\n$$
    NaN                                                NaN                          NaN
    49509                                              KOCO LIFE                    NaN
                                                       KOCO LIFE                    NaN

                                                                             Unnamed: 62  \
NaN NaN                                                NaN                           NaN
                                                       NaN                           NaN
                                                       NaN                           NaN
                                                       NaN                           NaN
    KOCO LIFE (49509)                                  NaN                           NaN
     Please Note:  Inventory values are from a snap... NaN                           NaN
    Vendor #                                           Vendor Name  STORE\nEOH $$ Chg\n%
    NaN                                                NaN                           NaN
    49509                                              KOCO LIFE                     NaN
                                                       KOCO LIFE                     NaN

                                                                               Unnamed: 63  \
NaN NaN                                                NaN                             NaN
                                                       NaN                             NaN
                                                       NaN                             NaN
                                                       NaN                             NaN
    KOCO LIFE (49509)                                  NaN                             NaN
     Please Note:  Inventory values are from a snap... NaN                             NaN
    Vendor #                                           Vendor Name  STORE\nEOH Comp\nUnits
    NaN                                                NaN                           18959
    49509                                              KOCO LIFE                      2074
                                                       KOCO LIFE                         1

                                                                                   Unnamed: 64  \
NaN NaN                                                NaN                                 NaN
                                                       NaN                                 NaN
                                                       NaN                                 NaN
                                                       NaN                                 NaN
    KOCO LIFE (49509)                                  NaN                                 NaN
     Please Note:  Inventory values are from a snap... NaN                                 NaN
    Vendor #                                           Vendor Name  STORE\nEOH Non-Comp\nUnits
    NaN                                                NaN                                2058
    49509                                              KOCO LIFE                           266
                                                       KOCO LIFE                             1

                                                                               Unnamed: 65  \
NaN NaN                                                NaN                             NaN
                                                       NaN                             NaN
                                                       NaN                             NaN
                                                       NaN                             NaN
    KOCO LIFE (49509)                                  NaN                             NaN
     Please Note:  Inventory values are from a snap... NaN                             NaN
    Vendor #                                           Vendor Name  STORE\nOn Order\nUnits
    NaN                                                NaN                            1784
    49509                                              KOCO LIFE                        43
                                                       KOCO LIFE                         0

                                                                                 Unnamed: 66  \
NaN NaN                                                NaN                               NaN
                                                       NaN                               NaN
                                                       NaN                               NaN
                                                       NaN                               NaN
    KOCO LIFE (49509)                                  NaN                               NaN
     Please Note:  Inventory values are from a snap... NaN                               NaN
    Vendor #                                           Vendor Name  STORE\nIn Transit\nUnits
    NaN                                                NaN                               501
    49509                                              KOCO LIFE                          30
                                                       KOCO LIFE                           0

                                                                                               Unnamed: 67  \
NaN NaN                                                NaN                                             NaN
                                                       NaN                                             NaN
                                                       NaN                                             NaN
                                                       NaN                                             NaN
    KOCO LIFE (49509)                                  NaN                                             NaN
     Please Note:  Inventory values are from a snap... NaN                                             NaN
    Vendor #                                           Vendor Name  STORE\nAvg Sales \n(Last 5 Wks)\nUnits
    NaN                                                NaN                                         753.717
    49509                                              KOCO LIFE                                     124.8
                                                       KOCO LIFE                                     13.75

                                                                         Unnamed: 68  \
NaN NaN                                                NaN                       NaN
                                                       NaN                       NaN
                                                       NaN                       NaN
                                                       NaN                       NaN
    KOCO LIFE (49509)                                  NaN                       NaN
     Please Note:  Inventory values are from a snap... NaN                       NaN
    Vendor #                                           Vendor Name  STORE\nComp\nWOS
    NaN                                                NaN                   26.0922
    49509                                              KOCO LIFE             17.4874
                                                       KOCO LIFE           0.0714286

                                                                              Unnamed: 69  \
NaN NaN                                                NaN                            NaN
                                                       NaN                            NaN
                                                       NaN                            NaN
                                                       NaN                            NaN
    KOCO LIFE (49509)                                  NaN                            NaN
     Please Note:  Inventory values are from a snap... NaN                            NaN
    Vendor #                                           Vendor Name  STORE\nNon-Comp \nWOS
    NaN                                                NaN                        92.9516
    49509                                              KOCO LIFE                  29.9032
                                                       KOCO LIFE                       -1

                                                                          Unnamed: 70
NaN NaN                                                NaN                        NaN
                                                       NaN                        NaN
                                                       NaN                        NaN
                                                       NaN                        NaN

In [8]:
date_range = df_result['Weekly Sales and Inventory Report'][1]
week_no = date_range[12]
date_from = date_range[15:25]
date_to = date_range[29:]

In [10]:

# mapping = {
#     "TOTAL\\nSales TY\\nUnits":"TSU",
#     "TOTAL\\nSales LY\\nUnits":"TOTAL Sales LY Units",
#     "TOTAL\\nSales chg\\n%":"TOTAL Sales chg %",
#     "TOTAL\\nSales TY\\n$$":"TOTAL Sales TY $$", 
#     "TOTAL\\nSales LY\\n$$":"TOTAL Sales LY $$",
#     "TOTAL\\nSales chg\\n%.1":"TOTAL Sales chg %.1",
#     "COMP\\nSales TY\\nUnits":"COMP Sales TY Units",
#     "COMP\\nSales LY\\nUnits":"COMP Sales LY Units",
#     "COMP\\nSales chg\\n%":"COMP Sales chg %",
#     "COMP\\nSales TY\\n$$":"COMP Sales TY $$",
#     "COMP\\nSales LY\\n$$":"COMP Sales LY $$",
#     "COMP\\nSales chg\\n%.1":"COMP Sales chg %.1",
#     "NONCOMP\\nSales TY\\nUnits":"NONCOMP Sales TY Units",
#     "NONCOMP\\nSales LY\\nUnits":"NONCOMP Sales LY Units",
#     "NONCOMP\\nSales chg\\n%":"NONCOMP Sales chg %",
#     "NONCOMP\\nSales TY\\n$$":"NONCOMP Sales TY $$",
#     "NONCOMP\\nSales LY\\n$$":"NONCOMP Sales LY $$",
#     "NONCOMP\\nSales chg\\n%.1":"NONCOMP Sales chg %.1",
#     "DOTCOM\\nSales TY\\nUnits":"DOTCOM Sales TY Units",
#     "DOTCOM\\nSales LY\\nUnits":"DOTCOM Sales LY Units",
#     "DOTCOM\\nSales chg\\n%":"DOTCOM Sales chg %",
#     "DOTCOM\\nSales TY\\n$$":"DOTCOM Sales TY $$",
#     "DOTCOM\\nSales LY\\n$$":"DOTCOM Sales LY $$",
#     "DOTCOM\\nSales chg\\n%.1":"DOTCOM Sales chg %.1" }
# df_result1.rename(columns=mapping,inplace=True)
desired_cols = [3,4, 15,16,19,22,25,28,31,34,37,40]
result1 = pd.read_excel("Sales and Inventory Report - 2018 FW06 - KOCO LIFE (49509).xlsx", sheetname=0, skiprows=(7),usecols = desired_cols)
df_result1 = pd.DataFrame(result1)


df_result1.columns = ['sku_number', 'item_description', 'purchase_cost', 'retail_price', 'total_sales_units', 'total_sales',
                     'comp_sales_units', 'comp_sales', 'non_comp_sales_units', 'non_comp_sales', 'dot_com_sales_units', 'dot_com_sales']

# df_result1.fillna(0)
# # df_result1 = df_result1.apply(f, axis=1)
# # df_result1 = df_result1.apply(pd.to_numeric,errors='coerce').fillna(0,downcast='infer')
# df_json = df_result1.to_json(orient="records", lines=True)
# df_json
# # df_result1

In [11]:
df_result2 = df_result1.iloc[1:]
df_result2 = df_result2.fillna(0)
df_result2

,sku_number,item_description,purchase_cost,retail_price,total_sales_units,total_sales,comp_sales_units,comp_sales,non_comp_sales_units,non_comp_sales,dot_com_sales_units,dot_com_sales
1,2523646.0,KOPARI COCONUT ROSE TONER 5.10OZ,11.52,24.00,278,6197.80,262,5826.14,16.0,371.66,63.0,1420.11
2,2523647.0,KOPARI COCONUT MULTITASKING KIT.COM,19.20,40.00,5,187.89,5,187.89,0.0,0.00,7.0,266.43
3,2523648.0,KOPARI COCONUT FACE CREAM 2.5OZ,18.24,38.00,191,6902.01,179,6487.65,12.0,414.36,33.0,1165.44
4,2523650.0,KOPARI COCONUT BODY GLOW 3.4OZ.COM,20.16,42.00,17,640.83,17,640.83,0.0,0.00,17.0,640.83
5,2523651.0,KOPARI COCONUT KISS KIT,14.40,30.00,21,550.16,21,550.16,0.0,0.00,21.0,550.16
6,2523652.0,KOPARI COCONUT LIP GLOSSY .35OZ.COM,5.76,12.00,4,46.11,5,58.11,-1.0,-12.00,6.0,70.11
7,2523653.0,KOPARI COCONUT CLEANSING OIL 5.1OZ,15.36,32.00,201,6037.21,191,5727.78,10.0,309.43,50.0,1448.49
8,2523654.0,KOPARI COCONUT MELT 5.1OZ,13.44,28.00,455,11603.17,417,10638.63,38.0,964.54,86.0,2136.18
9,2523655.0,KOPARI COCONUT MINI MELT 2.5OZ.COM,8.64,18.00,25,413.76,25,413.76,0.0,0.00,25.0,413.76
10,2523656.0,KOPARI COCONUT CRUSH SCRUB 10OZ.COM,18.24,38.00,11,376.38,11,376.38,0.0,0.00,11.0,376.38
11,2527818.0,KOPARI SAVE FACE OIL 1.7OZ,21.12,44.00,25,979.14,25,979.14,0.0,0.00,16.0,639.91
12,2527526.0,KOPARI MINI ROSE TONER 2OZ GWP,0.01,0.01,37,0.26,37,0.26,0.0,0.00,0.0,0.00
13,2528215.0,KOPARI FACE THE DAY AND NIGHT KIT.COM,19.20,40.00,32,1065.65,32,1065.65,0.0,0.00,32.0,1065.65

In [12]:
data1 = df_result2.to_dict('records')
data1

[{'comp_sales': 5826.14,
  'comp_sales_units': 262,
  'dot_com_sales': 1420.11,
  'dot_com_sales_units': 63.0,
  'item_description': 'KOPARI  COCONUT ROSE TONER 5.10OZ',
  'non_comp_sales': 371.66,
  'non_comp_sales_units': 16.0,
  'purchase_cost': 11.52,
  'retail_price': 24.0,
  'sku_number': 2523646.0,
  'total_sales': 6197.8,
  'total_sales_units': 278},
 {'comp_sales': 187.89,
  'comp_sales_units': 5,
  'dot_com_sales': 266.43,
  'dot_com_sales_units': 7.0,
  'item_description': 'KOPARI COCONUT MULTITASKING KIT.COM',
  'non_comp_sales': 0.0,
  'non_comp_sales_units': 0.0,
  'purchase_cost': 19.2,
  'retail_price': 40.0,
  'sku_number': 2523647.0,
  'total_sales': 187.89,
  'total_sales_units': 5},
 {'comp_sales': 6487.65,
  'comp_sales_units': 179,
  'dot_com_sales': 1165.44,
  'dot_com_sales_units': 33.0,
  'item_description': 'KOPARI COCONUT FACE CREAM 2.5OZ',
  'non_comp_sales': 414.36,
  'non_comp_sales_units': 12.0,
  'purchase_cost': 18.24,
  'retail_price': 38.0,
  'sku_number': 2523648.0,
  'total_sales': 6902.01,
  'total_sales_units': 191},
 {'comp_sales': 640.83,
  'comp_sales_units': 17,
  'dot_com_sales': 640.83,
  'dot_com_sales_units': 17.0,
  'item_description': 'KOPARI COCONUT BODY GLOW 3.4OZ.COM',
  'non_comp_sales': 0.0,
  'non_comp_sales_units': 0.0,
  'purchase_cost': 20.16,
  'retail_price': 42.0,
  'sku_number': 2523650.0,
  'total_sales': 640.83,
  'total_sales_units': 17},
 {'comp_sales': 550.16,
  'comp_sales_units': 21,
  'dot_com_sales': 550.16,
  'dot_com_sales_units': 21.0,
  'item_description': 'KOPARI COCONUT KISS KIT',
  'non_comp_sales': 0.0,
  'non_comp_sales_units': 0.0,
  'purchase_cost': 14.4,
  'retail_price': 30.0,
  'sku_number': 2523651.0,
  'total_sales': 550.16,
  'total_sales_units': 21},
 {'comp_sales': 58.11,
  'comp_sales_units': 5,
  'dot_com_sales': 70.11,
  'dot_com_sales_units': 6.0,
  'item_description': 'KOPARI COCONUT LIP GLOSSY .35OZ.COM',
  'non_comp_sales': -12.0,
  'non_comp_sales_units': -1.0,
  'purchase_cost': 5.76,
  'retail_price': 12.0,
  'sku_number': 2523652.0,
  'total_sales': 46.11,
  'total_sales_units': 4},
 {'comp_sales': 5727.78,
  'comp_sales_units': 191,
  'dot_com_sales': 1448.49,
  'dot_com_sales_units': 50.0,
  'item_description': 'KOPARI COCONUT CLEANSING OIL 5.1OZ',
  'non_comp_sales': 309.43,
  'non_comp_sales_units': 10.0,
  'purchase_cost': 15.36,
  'retail_price': 32.0,
  'sku_number': 2523653.0,
  'total_sales': 6037.21,
  'total_sales_units': 201},
 {'comp_sales': 10638.63,
  'comp_sales_units': 417,
  'dot_com_sales': 2136.18,
  'dot_com_sales_units': 86.0,
  'item_description': 'KOPARI COCONUT MELT 5.1OZ',
  'non_comp_sales': 964.54,
  'non_comp_sales_units': 38.0,
  'purchase_cost': 13.44,
  'retail_price': 28.0,
  'sku_number': 2523654.0,
  'total_sales': 11603.17,
  'total_sales_units': 455},
 {'comp_sales': 413.76,
  'comp_sales_units': 25,
  'dot_com_sales': 413.76,
  'dot_com_sales_units': 25.0,
  'item_description': 'KOPARI COCONUT MINI MELT 2.5OZ.COM',
  'non_comp_sales': 0.0,
  'non_comp_sales_units': 0.0,
  'purchase_cost': 8.64,
  'retail_price': 18.0,
  'sku_number': 2523655.0,
  'total_sales': 413.76,
  'total_sales_units': 25},
 {'comp_sales': 376.38,
  'comp_sales_units': 11,
  'dot_com_sales': 376.38,
  'dot_com_sales_units': 11.0,
  'item_description': 'KOPARI COCONUT CRUSH SCRUB 10OZ.COM',
  'non_comp_sales': 0.0,
  'non_comp_sales_units': 0.0,
  'purchase_cost': 18.24,
  'retail_price': 38.0,
  'sku_number': 2523656.0,
  'total_sales': 376.38,
  'total_sales_units': 11},
 {'comp_sales': 979.14,
  'comp_sales_units': 25,
  'dot_com_sales': 639.91,
  'dot_com_sales_units': 16.0,
  'item_description': 'KOPARI SAVE FACE OIL 1.7OZ',
  'non_comp_sales': 0.0,
  'non_comp_sales_units': 0.0,
  'purchase_cost': 21.12,
  'retail_price': 44.0,
  'sku_number': 2527818.0,
  'total_sales': 979.14,
  'total_sales_units': 25},
 {'comp_sales': 0.26,
  'comp_sales_units': 37,
  'dot_com_sales': 0.0,
  'dot_com_sales_units': 0.0,
  'item_description': 'KOPARI MINI ROSE TONER 2OZ GWP',
  'non_comp_sales': 0.0,
  'non_comp_sales_units': 0.0,
  'purchase_cost': 0.01,
  'retail_price': 0.01,
  'sku_number': 2527526.0,
  'total_sales': 0.26,
  'total_sales_units': 37},
 {'comp_sales': 1065.65,
  'comp_sales_units': 32,
  'dot_com_sales': 1065.65,
  'dot_com_sales_units': 32.0,
  'item_description': 'KOPARI FACE THE DAY AND NIGHT KIT.COM',
  'non_comp_sales': 0.0,
  'non_comp_sales_units': 0.0,
  'purchase_cost': 19.2,
  'retail_price': 40.0,
  'sku_number': 2528215.0,
  'total_sales': 1065.65,
  'total_sales_units': 32}]

In [18]:
bq_client = bigquery.Client()
projectId = 'sarasmaster-201918'
dataset_id = 'kopari'
table_id = 'ulta_test'

dataset_ref = bq_client.dataset(dataset_id)
table_ref = dataset_ref.table(table_id)

table = bq_client.get_table(table_ref)  # API Request

In [ ]:
json_rows = []
for index, row in df_result2.iterrows():
    data = df_result2.iloc[index-1]
#     data = df_result2.iloc[index-1].to_json(orient="records",lines=True)
#     json_rows  df_result2.iloc[0].to_json(orient="records")
#     print(data)
#     errors = bq_client.insert_rows(table, json_data)
# print(json_rows)

In [19]:
# errors = bq_client.insert_rows(table, data1)  # API request
errors = bq_client.insert_rows_json(table, data1)

assert errors == []
errors

[]