In [1]:
# !pip uninstall google-api-core
# !pip install google-cloud-bigquery
# !pip install google-cloud
from google.cloud import bigquery
from google.cloud import storage

In [2]:
import email
import getpass,imaplib
import os
import sys
import numpy as np
import pandas as pd
import json
import pandas.io.gbq as gbq
from google.cloud import bigquery

In [3]:
detach_dir = '.'

In [4]:
if 'attachments' not in os.listdir(detach_dir):
    os.mkdir('attachments')

In [5]:
userName = 'codebalanceit@gmail.com'
password = 'Hari@coding'
userName

'codebalanceit@gmail.com'

In [6]:
imapSession = imaplib.IMAP4_SSL('imap.gmail.com')
typ, accountDetails = imapSession.login(userName, password)

imapSession.select()
typ, data = imapSession.search(None, '(FROM "Sreehari Nambiar") UNSEEN')

# iterate over all emails
for msgId in data[0].split():
    typ, messageParts = imapSession.fetch(msgId, '(RFC822)')
    # print(emailBody)
    emailBody = messageParts[0][1]
    mail = email.message_from_bytes(emailBody)
    for part in mail.walk():
        if part.get_content_maintype() == 'multipart':
            # print part.as_string()
            continue
        if part.get('Content-Disposition') is None:
            # print part.as_string()
            continue
        fileName = part.get_filename()
        #print(fileName)
        
            
        if bool(fileName):
            filePath = os.path.join(detach_dir, 'attachments', fileName)
            if not os.path.isfile(filePath):
                #print(filePath) 
                fp = open(filePath, 'wb')
                fp.write(part.get_payload(decode=True))
                fp.close()
    imapSession.store(msgId, '+FLAGS', '\Seen')
            
imapSession.close()
imapSession.logout()

## update control table

('BYE', [b'LOGOUT Requested'])

In [7]:
fileName

'Sales and Inventory Report - 2018 FW06 - KOCO LIFE (49509).xlsx'

In [8]:
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="/Users/Guest/Desktop/python-google/sarasmaster-a88d695c46b1.json"

In [9]:
# Import the Google Cloud client Library
from google.cloud import storage
from google.cloud.exceptions import NotFound

In [ ]:
def upload_blob(bucket_name, source_file_name, destination_blob_name):
    # upload a file to bucket
    # Initiate a client
    storage_client = storage.Client()
    bucket = storage_client.get_bucket(bucket_name)
    blob = bucket.blob(destination_blob_name)
    
    blob.upload_from_filename(source_file_name)
    
    print('File {} uploaded to {}.'.format(source_file_name,
        destination_blob_name))

In [ ]:
upload_blob('sarasmaster', fileName, 'kopari/retail/ulta/ulta_sales.xls')

In [10]:
import pandas as pd
import json
import pandas.io.gbq as gbq
from google.cloud import bigquery
# desired_cols = [1] + list(range(19,43))
result = pd.read_excel(fileName, sheetname=0)
df_result = pd.DataFrame(result)
df_result.head(10)

/Users/Guest/anaconda3/lib/python3.6/site-packages/pandas/util/_decorators.py:118: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  return func(*args, **kwargs)

                                                                         Weekly Sales and Inventory Report  \
NaN NaN                                                NaN            Last Closed Week Sales and Inventory
                                                       NaN          Fiscal Week 6: 03/11/2018 - 03/17/2018
                                                       NaN                                             NaN
                                                       NaN                                             NaN
    KOCO LIFE (49509)                                  NaN                                             NaN
     Please Note:  Inventory values are from a snap... NaN                                             NaN
    Vendor #                                           Vendor Name                             Item Number
    NaN                                                NaN                                             NaN
    49509                                              KOCO LIFE                                   2523646
                                                       KOCO LIFE                                   2523647

                                                                                             Unnamed: 1  \
NaN NaN                                                NaN                                          NaN
                                                       NaN                                          NaN
                                                       NaN                                          NaN
                                                       NaN                                          NaN
    KOCO LIFE (49509)                                  NaN                                          NaN
     Please Note:  Inventory values are from a snap... NaN                                          NaN
    Vendor #                                           Vendor Name                     Item Description
    NaN                                                NaN                                          NaN
    49509                                              KOCO LIFE      KOPARI  COCONUT ROSE TONER 5.10OZ
                                                       KOCO LIFE    KOPARI COCONUT MULTITASKING KIT.COM

                                                                   Unnamed: 2  \
NaN NaN                                                NaN                NaN
                                                       NaN                NaN
                                                       NaN                NaN
                                                       NaN                NaN
    KOCO LIFE (49509)                                  NaN                NaN
     Please Note:  Inventory values are from a snap... NaN                NaN
    Vendor #                                           Vendor Name        Div
    NaN                                                NaN                NaN
    49509                                              KOCO LIFE            1
                                                       KOCO LIFE            1

                                                                   Unnamed: 3  \
NaN NaN                                                NaN                NaN
                                                       NaN                NaN
                                                       NaN                NaN
                                                       NaN                NaN
    KOCO LIFE (49509)                                  NaN                NaN
     Please Note:  Inventory values are from a snap... NaN                NaN
    Vendor #                                           Vendor Name       Dept
    NaN                                                NaN                NaN
    49509                                              KOCO LIFE           14
                                                       KOCO LIFE           14

                                                                   Unnamed: 4  \
NaN NaN                                                NaN                NaN
                                                       NaN                NaN
                                                       NaN                NaN
                                                       NaN                NaN
    KOCO LIFE (49509)                                  NaN                NaN
     Please Note:  Inventory values are from a snap... NaN                NaN
    Vendor #                                           Vendor Name      Class
    NaN                                                NaN                NaN
    49509                                              KOCO LIFE          115
                                                       KOCO LIFE          116

                                                                   Unnamed: 5  \
NaN NaN                                                NaN                NaN
                                                       NaN                NaN
                                                       NaN                NaN
                                                       NaN                NaN
    KOCO LIFE (49509)                                  NaN                NaN
     Please Note:  Inventory values are from a snap... NaN                NaN
    Vendor #                                           Vendor Name  Sub Class
    NaN                                                NaN                NaN
    49509                                              KOCO LIFE         2168
                                                       KOCO LIFE         1172

                                                                    Unnamed: 6  \
NaN NaN                                                NaN                 NaN
                                                       NaN                 NaN
                                                       NaN                 NaN
                                                       NaN                 NaN
    KOCO LIFE (49509)                                  NaN                 NaN
     Please Note:  Inventory values are from a snap... NaN                 NaN
    Vendor #                                           Vendor Name  Item\nRank
    NaN                                                NaN                 NaN
    49509                                              KOCO LIFE             F
                                                       KOCO LIFE             #

                                                                               Unnamed: 7  \
NaN NaN                                                NaN                            NaN
                                                       NaN                            NaN
                                                       NaN                            NaN
                                                       NaN                            NaN
    KOCO LIFE (49509)                                  NaN                            NaN
     Please Note:  Inventory values are from a snap... NaN                            NaN
    Vendor #                                           Vendor Name  Store\nCount\n(Total)
    NaN                                                NaN                            NaN
    49509                                              KOCO LIFE                     1096
                                                       KOCO LIFE                      NaN

                                                                      Unnamed: 8  \
NaN NaN                                                NaN                   NaN
                                                       NaN                   NaN
                                                       NaN                   NaN
                                                       NaN                   NaN
    KOCO LIFE (49509)                                  NaN                   NaN
     Please Note:  Inventory values are from a snap... NaN                   NaN
    Vendor #                                           Vendor Name           UPC
    NaN                                                NaN                   NaN
    49509                                              KOCO LIFE    851989006084
                                                       KOCO LIFE    851989006282

                                                                         Unnamed: 9  \
NaN NaN                                                NaN                      NaN
                                                       NaN                      NaN
                                                       NaN                      NaN
                                                       NaN                      NaN
    KOCO LIFE (49509)                                  NaN                      NaN
     Please Note:  Inventory values are from a snap... NaN                      NaN
    Vendor #                                           Vendor Name  Vendor Part No.
    NaN                                                NaN                      NaN
    49509                                              KOCO LIFE           KRT-0150
                                                       KOCO LIFE           KMK-0200

                                                                          ...          \
NaN NaN                                                NaN                ...
                                                       NaN                ...
                                                       NaN                ...
                                                       NaN                ...
    KOCO LIFE (49509)                                  NaN                ...
     Please Note:  Inventory values are from a snap... NaN                ...
    Vendor #                                           Vendor Name        ...
    NaN                                                NaN                ...
    49509                                              KOCO LIFE          ...
                                                       KOCO LIFE          ...

                                                                            Unnamed: 61  \
NaN NaN                                                NaN                          NaN
                                                       NaN                          NaN
                                                       NaN                          NaN
                                                       NaN                          NaN
    KOCO LIFE (49509)                                  NaN                          NaN
     Please Note:  Inventory values are from a snap... NaN                          NaN
    Vendor #                                           Vendor Name  STORE\nEOH (LY)\n$$
    NaN                                                NaN                          NaN
    49509                                              KOCO LIFE                    NaN
                                                       KOCO LIFE                    NaN

                                                                             Unnamed: 62  \
NaN NaN                                                NaN                           NaN
                                                       NaN                           NaN
                                                       NaN                           NaN
                                                       NaN                           NaN
    KOCO LIFE (49509)                                  NaN                           NaN
     Please Note:  Inventory values are from a snap... NaN                           NaN
    Vendor #                                           Vendor Name  STORE\nEOH $$ Chg\n%
    NaN                                                NaN                           NaN
    49509                                              KOCO LIFE                     NaN
                                                       KOCO LIFE                     NaN

                                                                               Unnamed: 63  \
NaN NaN                                                NaN                             NaN
                                                       NaN                             NaN
                                                       NaN                             NaN
                                                       NaN                             NaN
    KOCO LIFE (49509)                                  NaN                             NaN
     Please Note:  Inventory values are from a snap... NaN                             NaN
    Vendor #                                           Vendor Name  STORE\nEOH Comp\nUnits
    NaN                                                NaN                           18959
    49509                                              KOCO LIFE                      2074
                                                       KOCO LIFE                         1

                                                                                   Unnamed: 64  \
NaN NaN                                                NaN                                 NaN
                                                       NaN                                 NaN
                                                       NaN                                 NaN
                                                       NaN                                 NaN
    KOCO LIFE (49509)                                  NaN                                 NaN
     Please Note:  Inventory values are from a snap... NaN                                 NaN
    Vendor #                                           Vendor Name  STORE\nEOH Non-Comp\nUnits
    NaN                                                NaN                                2058
    49509                                              KOCO LIFE                           266
                                                       KOCO LIFE                             1

                                                                               Unnamed: 65  \
NaN NaN                                                NaN                             NaN
                                                       NaN                             NaN
                                                       NaN                             NaN
                                                       NaN                             NaN
    KOCO LIFE (49509)                                  NaN                             NaN
     Please Note:  Inventory values are from a snap... NaN                             NaN
    Vendor #                                           Vendor Name  STORE\nOn Order\nUnits
    NaN                                                NaN                            1784
    49509                                              KOCO LIFE                        43
                                                       KOCO LIFE                         0

                                                                                 Unnamed: 66  \
NaN NaN                                                NaN                               NaN
                                                       NaN                               NaN
                                                       NaN                               NaN
                                                       NaN                               NaN
    KOCO LIFE (49509)                                  NaN                               NaN
     Please Note:  Inventory values are from a snap... NaN                               NaN
    Vendor #                                           Vendor Name  STORE\nIn Transit\nUnits
    NaN                                                NaN                               501
    49509                                              KOCO LIFE                          30
                                                       KOCO LIFE                           0

                                                                                               Unnamed: 67  \
NaN NaN                                                NaN                                             NaN
                                                       NaN                                             NaN
                                                       NaN                                             NaN
                                                       NaN                                             NaN
    KOCO LIFE (49509)                                  NaN                                             NaN
     Please Note:  Inventory values are from a snap... NaN                                             NaN
    Vendor #                                           Vendor Name  STORE\nAvg Sales \n(Last 5 Wks)\nUnits
    NaN                                                NaN                                         753.717
    49509                                              KOCO LIFE                                     124.8
                                                       KOCO LIFE                                     13.75

                                                                         Unnamed: 68  \
NaN NaN                                                NaN                       NaN
                                                       NaN                       NaN
                                                       NaN                       NaN
                                                       NaN                       NaN
    KOCO LIFE (49509)                                  NaN                       NaN
     Please Note:  Inventory values are from a snap... NaN                       NaN
    Vendor #                                           Vendor Name  STORE\nComp\nWOS
    NaN                                                NaN                   26.0922
    49509                                              KOCO LIFE             17.4874
                                                       KOCO LIFE           0.0714286

                                                                              Unnamed: 69  \
NaN NaN                                                NaN                            NaN
                                                       NaN                            NaN
                                                       NaN                            NaN
                                                       NaN                            NaN
    KOCO LIFE (49509)                                  NaN                            NaN
     Please Note:  Inventory values are from a snap... NaN                            NaN
    Vendor #                                           Vendor Name  STORE\nNon-Comp \nWOS
    NaN                                                NaN                        92.9516
    49509                                              KOCO LIFE                  29.9032
                                                       KOCO LIFE                       -1

                                                                          Unnamed: 70
NaN NaN                                                NaN                        NaN
                                                       NaN                        NaN
                                                       NaN                        NaN
                                                       NaN                        NaN

In [11]:
date_range = df_result['Weekly Sales and Inventory Report'][1]
week_no = date_range[12]
date_from = date_range[15:25].replace('/','')
date_to = date_range[29:].replace('/','')

In [12]:

desired_cols = [12,4, 15,16,19,22,25,28,31,34,37,40]
result1 = pd.read_excel("Sales and Inventory Report - 2018 FW06 - KOCO LIFE (49509).xlsx", sheetname=0, skiprows=(7),usecols = desired_cols)
df_result1 = pd.DataFrame(result1)
df_result1.columns = ['item_description','sku_number', 'purchase_cost', 'retail_price', 'total_sales_units', 'total_sales','comp_sales_units', 'comp_sales', 'non_comp_sales_units', 'non_comp_sales', 'dot_com_sales_units', 'dot_com_sales']

/Users/Guest/anaconda3/lib/python3.6/site-packages/pandas/util/_decorators.py:118: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  return func(*args, **kwargs)

In [13]:
df_result2 = df_result1.iloc[1:]
df_result2 = df_result2.fillna(0)
# df_result2

In [14]:
for row in df_result2.iterrows():
    df_result2['year'] = date_to[-4:0]
    df_result2['qtr'] = 'Q'+ str((int(date_to[0:-6])+2)//3)
    df_result2['week'] = week_no   
    df_result2['qtr']

In [15]:
jsonFileName = 'Kopari_'+date_from+'_to_'+date_to+'.json'
df_result2.to_json(path_or_buf='/Users/Guest/Desktop/python-google/'+jsonFileName, orient='records')
jsonFileName

'Kopari_03112018_to_3172018.json'

In [ ]:
data1 = df_result2.to_dict('records')
# data1

In [16]:
bq_client = bigquery.Client()
projectId = 'sarasmaster-201918'
dataset_id = 'kopari'
table_id = 'ulta_sales_copy'

dataset_ref = bq_client.dataset(dataset_id)
table_ref = dataset_ref.table(table_id)

table = bq_client.get_table(table_ref)  # API Request
table_ref

TableReference('sarasmaster-201918', 'kopari', 'ulta_sales_copy')

In [17]:
previous_rows = bq_client.get_table(table_ref).num_rows
job_config = bigquery.LoadJobConfig()
job_config.source_format = bigquery.SourceFormat.NEWLINE_DELIMITED_JSON
job_config.write_disposition = bigquery.WriteDisposition.WRITE_APPEND

load_job = bq_client.load_table_from_uri(
    jsonFileName,
    table_ref,
    job_config=job_config)  # API request

assert load_job.job_type == 'load'

load_job.result()  # Waits for table load to complete.

assert load_job.state == 'DONE'

AttributeError: module 'google.cloud.bigquery' has no attribute 'SourceFormat'

In [ ]:
json_rows = []
for row in df_result2.iterrows():
    data = df_result2.iloc[index-1]
#     data = df_result2.iloc[index-1].to_json(orient="records",lines=True)
#     json_rows  df_result2.iloc[0].to_json(orient="records")
#     print(data)
#     errors = bq_client.insert_rows(table, json_data)
# print(json_rows)

In [ ]:
# errors = bq_client.insert_rows(table, data1)  # API request
errors = bq_client.insert_rows_json(table, data1)

assert errors == []
errors

In [ ]:
# client = bigquery.Client()
# table_ref = client.dataset('my_dataset').table('existing_table')previous_rows = client.get_table(table_ref).num_rows

#job_config.source_format = bigquery.SourceFormat.NEWLINE_DELIMITED_JSON
#job_config.write_disposition = bigquery.WriteDisposition.WRITE_APPEND

with open("bigquery.SourceFormat", mode='r') as f:
    f.read()